<?php

namespace ContainerBuklub4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrangeKangarooControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OrangeKangarooController' shared autowired service.
     *
     * @return \App\Controller\OrangeKangarooController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/OrangeKangarooController.php';

        $container->services['App\\Controller\\OrangeKangarooController'] = $instance = new \App\Controller\OrangeKangarooController(($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService')));

        $instance->setContainer(($container->privates['.service_locator.SuLO6WU'] ?? $container->load('get_ServiceLocator_SuLO6WUService'))->withContext('App\\Controller\\OrangeKangarooController', $container));

        return $instance;
    }
}
